name: ${COMPOSE_PROJECT_NAME}

services:
  nginx:
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - type: bind
        source: ./sfapi
        target: /app/sfapi
    depends_on:
      - sfapi
    ports:
      - 8000:80
    networks:
      - network
  sfapi:
    build:
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME:-0}
        GROUP_NAME: ${GROUP_NAME:-0}
      context: .
      dockerfile: ./build/sfapi/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-sfapi
    container_name: ${COMPOSE_PROJECT_NAME}-sfapi
    volumes:
      - type: bind
        source: ./sfapi
        target: /app/sfapi
    depends_on:
      - database
    networks:
      - network
  database:
    build:
      context: .
      dockerfile: ./build/database/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-database
    container_name: ${COMPOSE_PROJECT_NAME}-database
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    networks:
      - network

  front:
    image: node:20-alpine
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      # Nginx s'appelle "nginx" dans le réseau docker
      NUXT_PUBLIC_API_BASE: http://nginx:80
    volumes:
      - ./front:/app
    ports:
      - "3000:3000" # Front accessible sur localhost:3000
    command: sh -c "npm install && npm run dev"
    networks:
      - network

networks:
  network:
    name : ${COMPOSE_PROJECT_NAME}-network
    driver: bridge

volumes:
  database-volume:
    driver: local
